# Generated by Django 3.2.3 on 2021-07-02 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='media/about/%Y/%m/%d')),
            ],
        ),
    ]
