# Generated by Django 3.2.3 on 2021-07-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacttubers', '0002_alter_contacttuber_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttuber',
            name='user_id',
        ),
    ]
