# Generated by Django 3.2.3 on 2021-05-31 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/%m')),
                ('city', models.CharField(max_length=250)),
                ('Description', models.TextField()),
                ('fb_link', models.CharField(max_length=250)),
                ('insta_link', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('youtube_link', models.CharField(default='', max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
