# Generated by Django 3.2.3 on 2021-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='camera',
            field=models.CharField(choices=[('sony', 'sony'), ('canon', 'canon'), ('nikon', 'nikon'), ('fuji', 'fuji')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small crew', 'small crew'), ('large crew', 'large crew')], default='', max_length=250),
        ),
    ]
