# Generated by Django 3.2.3 on 2021-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210531_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('music', 'music'), ('education', 'education'), ('sports', 'sports'), ('cooking', 'cooking'), ('gaming', 'gaming'), ('vlogs', 'vlogs'), ('comedy', 'comedy')], default='', max_length=250),
        ),
    ]
