# Generated by Django 3.2.3 on 2021-05-31 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_youtuber_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
